---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: ros_indigo
    run_list:
      - recipe[ros_test::install_indigo]
      - recipe[ros_test::catkin_package]
    attributes:
  - name: ros_indigo_no_sysprofile
    run_list:
      - recipe[ros_test::install_indigo_no_sysprofile]
    attributes:
