sudo: required
services:
  - docker
cache: bundler
language: ruby
notifications:
  slack:
    secure: l+MM6GbdABbA3IfV2mRPBufUUG8zmvPkjx2zlIY7tvD7xrOre3vGmucPevQPv/yBj2tgICPWMNDqxLZNRZqC3zG8hJu5NocEqaG4lacdjHlOQm/17nxmMgm/7n3r9ymrS2rCBVcEw7ytUOZxxD6vLlFENN7bNBVpFIfrj4JX4qc=
before_install:
- openssl aes-256-cbc -K $encrypted_a17b55e0d87d_key -iv $encrypted_a17b55e0d87d_iv
  -in test/integration/travis_ssh_key.enc -out ~/.ssh/id_rsa -d
bundler_args: "--binstubs"
script:
- "./bin/foodcritic ."
- "./bin/kitchen test -d never" 
after_script:
- rm ~/.ssh/id_rsa
