name             'ros'
maintainer       'Ryan Hass'
maintainer_email 'ryan@invalidchecksum.net'
license          'Apache 2.0'
description      'Installs/Configures ros'
long_description 'Installs/Configures ros'
version          '0.3.1'

supports 'ubuntu'

depends 'apt', '>= 2.6.1'
depends 'poise', '~> 2.2.3'
depends 'locale'
depends 'build-essential'
depends 'supervisor'
